version: "3.8"

# Compose para los microservicios.
# Usa deploy/.env (no este .template) con valores reales. Cada servicio lee sus variables desde application.properties (server.port=${...}).
services:
  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    env_file:
      - .env
    ports:
      - "${EUREKA_SERVER_PORT:-8761}:${EUREKA_SERVER_PORT:-8761}"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME:-localhost}
    restart: unless-stopped
    networks:
      - backend

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    env_file:
      - .env
    ports:
      - "${API_GATEWAY_SERVER_PORT:-8090}:${API_GATEWAY_SERVER_PORT:-8090}"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - backend

  msvc-oauth:
    build:
      context: ../msvc-oauth
      dockerfile: Dockerfile
    image: msvc-oauth:latest
    env_file:
      - .env
    ports:
      - "${MSVC_OAUTH_SERVER_PORT:-9100}:${MSVC_OAUTH_SERVER_PORT:-9100}"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - backend

  msvc-users:
    build:
      context: ../msvc-users
      dockerfile: Dockerfile
    image: msvc-users:latest
    env_file:
      - .env
    ports:
      - "${MSVC_USERS_SERVER_PORT:-8081}:${MSVC_USERS_SERVER_PORT:-8081}"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - backend

  msvc-clientes:
    build:
      context: ../msvc-clientes
      dockerfile: Dockerfile
    image: msvc-clientes:latest
    env_file:
      - .env
    ports:
      - "${MSVC_CLIENTES_SERVER_PORT:-8082}:${MSVC_CLIENTES_SERVER_PORT:-8082}"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - backend

  msvc-vehiculos:
    build:
      context: ../msvc-vehiculos
      dockerfile: Dockerfile
    image: msvc-vehiculos:latest
    env_file:
      - .env
    ports:
      - "${MSVC_VEHICULOS_SERVER_PORT:-8083}:${MSVC_VEHICULOS_SERVER_PORT:-8083}"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - backend

  msvc-contratos:
    build:
      context: ../msvc-contratos
      dockerfile: Dockerfile
    image: msvc-contratos:latest
    env_file:
      - .env
    ports:
      - "${MSVC_CONTRATOS_SERVER_PORT:-8084}:${MSVC_CONTRATOS_SERVER_PORT:-8084}"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - backend

  msvc-reportes:
    build:
      context: ../msvc-reportes
      dockerfile: Dockerfile
    image: msvc-reportes:latest
    env_file:
      - .env
    ports:
      - "${MSVC_REPORTES_SERVER_PORT:-8085}:${MSVC_REPORTES_SERVER_PORT:-8085}"
    depends_on:
      - eureka-server
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge